# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
## OIDC_IDENTITY_PROVIDER_ISSUER_URL: "http://oidc.lab.pcfdemo.net:8000/realms/myrealm"
version: '2'
services:

  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:21
    depends_on:
      - postgresql
    ports:
      - "8443:8443"
    environment:
      - KEYCLOAK_ENABLE_HTTPS=true
      - KEYCLOAK_HTTPS_KEY_STORE_FILE=/opt/bitnami/keycloak/certs/keystore.jks
      - KEYCLOAK_HTTPS_KEY_STORE_PASSWORD=VMware1!
      - KEYCLOAK_HTTPS_TRUST_STORE_FILE=/opt/bitnami/keycloak/certs/truststore.jks
      - KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD=VMware1!
     # - KEYCLOAK_HTTPS_USE_PEM=true
      - KEYCLOAK_HTTPS_CERTIFICATE_FILE=/opt/bitnami/keycloak/certs/domain.crt
      - KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE=/opt/bitnami/keycloak/certs/domain.key
      - KC_LOG_LEVEL=info
    volumes:
      - '/data/keyclock/generate-self-signed-cert-keyclock/:/opt/bitnami/keycloak/certs/'


volumes:
  postgresql_data:
    driver: local
