kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv1
  labels:
    type: local
spec:
        #  storageClassName: local-storage 
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
