apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: local-storage
provisioner: kubernetes.io/no-provisioner
#provisioner: csi.vsphere.vmware.com
volumeBindingMode: WaitForFirstConsumer
