[ ca ]
default_ca = CA_default

[ CA_default ]
dir               = ./certs
database          = $dir/intermediate_index.txt
new_certs_dir     = $dir/.
serial            = $dir/intermediate_serial
private_key       = $dir/intermediate.key.pem
certificate       = $dir/intermediate.cert.pem
default_days      = 1825
default_md        = sha256
policy            = policy_loose
x509_extensions   = v3_intermediate_ca
default_crl_days  = 30

[ policy_loose ]
#countryName             = match
#stateOrProvinceName     = match
#organizationName        = match
commonName              = supplied

[ req ]
distinguished_name = req_distinguished_name
prompt = no

[ req_distinguished_name ]
C = KO
ST = Seoul
L = Seoul
O = ExampleOrg
OU = IntermediateCA
CN = ExampleOrg Intermediate CA #<--- EDIT this



[ v3_intermediate_ca ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid,issuer
basicConstraints = critical, CA:TRUE, pathlen:0
keyUsage = critical, digitalSignature, cRLSign, keyCertSign