kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # This option mounts the host docker registry folder into
    # the control-plane node, allowing containerd to access them. 
    extraMounts:
      - containerPath: /usr/local/share/ca-certificates/ca.crt
        hostPath: /etc/docker/certs.d/infra-harbor.lab.pcfdemo.net/ca.crt

